# 每月随机触发2次，防止 GitHub 因60天无活动自动禁用定时工作流
name: keepalive

on:
  workflow_dispatch:
  schedule:
    - cron: "43 7 4,22 * *" # 每月4号和22号 15:43 (UTC 7:43)

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Keepalive
        run: |
          echo "=> 发送 keepalive 信号..."
          gh api repos/susulqx/BiliBiliToolPro/actions/workflows \
            --jq '.total_count' > /dev/null
          echo "=> 完成"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
